version: "2"
plugins:
  # Disabling plugins until there is a reasonable way to sanitize their output
  phpcodesniffer:
    enabled: false
    config:
      standard: "PSR1,PSR2"
      ignore_warnings: true
      encoding: utf-8
  phpmd:
    enabled: false
  sonar-php:
    enabled: false

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 40
  method-count:
    config:
      threshold: 40
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 150
