ignore:
  - docs
  - examples
  - tests
  - tools
coverage:
  precision: 2
  round: down
  range: "95...100"
  status:
    project:
      default:
        threshold: 1%
        target: 100
        target: 95
    patch: yes
    changes: no
