ignore:
  - docs
  - examples
  - tests
  - tools
coverage:
  precision: 2
  round: down
  range: "95...100" # coverage expectations
  status:
    project:
      default:
        threshold: 1% # coverage diff threshold
        target: 100
        target: 95
    patch: yes
    changes: no
