<?php

// vim:ts=4:sw=4:et:fdm=marker

namespace atk4\core;

/**
 * All exceptions generated by Agile Toolkti will use this class.
 *
 * @license MIT
 * @copyright Agile Toolkit (c) http://agiletoolkit.org/
 */
class HookBreaker extends \Exception
{
    public $return_value = null;

    function __construct($rv) {
        $this->return_value = $rv;
    }
}
